<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="3" passed="2" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2023-01-09T13:37:29Z" name="Default suite" finished-at="2023-01-09T13:39:22Z" duration-ms="113111">
    <groups>
    </groups>
    <test started-at="2023-01-09T13:37:29Z" name="Default test" finished-at="2023-01-09T13:39:22Z" duration-ms="113111">
      <class name="com.app.test.AppTest">
        <test-method is-config="true" signature="setUp()[pri:0, instance:com.app.test.AppTest@25f4878b]" started-at="2023-01-09T19:07:29Z" name="setUp" finished-at="2023-01-09T19:07:36Z" duration-ms="6685" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="verifyBag()[pri:0, instance:com.app.test.AppTest@25f4878b]" started-at="2023-01-09T19:07:36Z" name="verifyBag" finished-at="2023-01-09T19:08:27Z" duration-ms="51035" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [1] but found [2]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [1] but found [2]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:190)
	at org.testng.Assert.assertEquals(Assert.java:200)
	at com.app.test.AppTest.verifyBag(AppTest.java:71)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyBag -->
        <test-method is-config="true" signature="teatDown()[pri:0, instance:com.app.test.AppTest@25f4878b]" started-at="2023-01-09T19:08:27Z" name="teatDown" finished-at="2023-01-09T19:08:28Z" duration-ms="755" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teatDown -->
        <test-method is-config="true" signature="setUp()[pri:0, instance:com.app.test.AppTest@25f4878b]" started-at="2023-01-09T19:08:28Z" name="setUp" finished-at="2023-01-09T19:08:33Z" duration-ms="5700" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="verifyLogin()[pri:0, instance:com.app.test.AppTest@25f4878b]" started-at="2023-01-09T19:08:33Z" name="verifyLogin" finished-at="2023-01-09T19:09:10Z" duration-ms="36483" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyLogin -->
        <test-method is-config="true" signature="teatDown()[pri:0, instance:com.app.test.AppTest@25f4878b]" started-at="2023-01-09T19:09:10Z" name="teatDown" finished-at="2023-01-09T19:09:11Z" duration-ms="790" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teatDown -->
        <test-method is-config="true" signature="setUp()[pri:0, instance:com.app.test.AppTest@25f4878b]" started-at="2023-01-09T19:09:11Z" name="setUp" finished-at="2023-01-09T19:09:18Z" duration-ms="7180" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="verifySearch()[pri:0, instance:com.app.test.AppTest@25f4878b]" started-at="2023-01-09T19:09:18Z" name="verifySearch" finished-at="2023-01-09T19:09:22Z" duration-ms="3701" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifySearch -->
        <test-method is-config="true" signature="teatDown()[pri:0, instance:com.app.test.AppTest@25f4878b]" started-at="2023-01-09T19:09:22Z" name="teatDown" finished-at="2023-01-09T19:09:22Z" duration-ms="758" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teatDown -->
      </class> <!-- com.app.test.AppTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
